workflows:
  ios-release:
    name: A.BABA iOS Release (App Store / TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Yalla Driver Key
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.hamakhorshed.ababa
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Generate App Icons
        script: |
          dart run flutter_launcher_icons
      - name: Install CocoaPods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build Flutter IPA
        script: |
          flutter build ipa --release \
            --build-name=1.0.1 \
            --build-number=3
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
