microservices:
  - name: auth-service
    image: ahmedbaba/auth-service
    tag: latest
    port: 8081
    replicas: 5
    env:
      - name: DATABASE_DSN
        value: "host=postgresql user=admin password=admin dbname=auth"

  - name: order-service
    image: ahmedbaba/order-service
    tag: latest
    port: 8082
    replicas: 10 # High scale for mission-critical escrow
    env:
      - name: DATABASE_DSN
        value: "host=postgresql user=admin password=admin dbname=orders"

  - name: catalog-service
    image: ahmedbaba/catalog-service
    tag: latest
    port: 8087
    replicas: 8
    env:
      - name: MONGO_URI
        value: "mongodb://mongodb:27017"
      - name: ELASTICSEARCH_URL
        value: "http://elasticsearch:9200"

# Ingress Configuration
ingress:
  enabled: true
  hostname: api.ahmedbaba.com
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
